### ISSUE TITLE
Feature: User can add and delete tv shows to their My Watchlist

### ISSUE THREAD

**Issue by Courtney-Lippman** [streamr-turing/streamr-fe#13]
As a user, when I am on the Homepage, Details view, or Search view. I want to add and remove tv shows to/from my Watchlist to find the tv shows I want to watch quickly.

![Image](https://user-images.githubusercontent.com/104169837/216783666-a4906835-2652-41e7-a56d-26db574aff80.png)

![Image](https://user-images.githubusercontent.com/104169837/216783681-55b4b823-b9b8-48d6-ba33-334b31509800.png)

![Image](https://user-images.githubusercontent.com/104169837/216783711-30fbed14-7892-400d-a10b-75366373229b.png)

Subtasks:

- [x] Add icons to the respective components with Onclick functionality

- [x] Add Onclick functionality that toggles the watchlist state from true to false and vice versa and changes the save/delete icon based on the watchlist state of the specific tv show.

**Comment by Courtney-Lippman** [comment]
Some questions that I have for this issue:

1. Should the favoriting functionality by FE or BE - How do we connect the favorite functionality to the BE so it persists on refresh for the user?
2. Do we want a heart icon that the user can click and it fills in which represents saving to watchlist and then the user can click again and that will then unfill representing deleting from watchlist? I personally think a plus and minus are more representative of adding and deleting for a watchlist. I think of heart fills as the user saying they like the movie.

**Comment by Courtney-Lippman** [comment]
For the second question stated above, @streamr-turing/frontend decided to use + and - bookmark icons for saving and deleting tv shows to the watchlist. As per the discussion, the bookmarks with a plus and minus will be apparent to the user on if they are adding or deleting the tv show to their watchlist.

**Comment by sam-rice** [comment]
> Some questions that I have for this issue:
> 
> 1. Should the favoriting functionality by FE or BE - How do we connect the favorite functionality to the BE so it persists on refresh for the user?
> 2. Do we want a heart icon that the user can click and it fills in which represents saving to watchlist and then the user can click again and that will then unfill representing deleting from watchlist? I personally think a plus and minus are more representative of adding and deleting for a watchlist. I think of heart fills as the user saying they like the movie.

1. If we go the route I suggested [here](https://github.com/streamr-turing/streamr-fe/issues/9#issuecomment-1416821733) (or something similar), we could use local storage to save the `currentUser` state once the user logs in. Then the logged-in state would persist until the user deliberately logs out. 
2. Yeah, I also prefer the bookmark icons for the same reasons.
