### ISSUE TITLE
Testing: Share Modal (wait)

### ISSUE THREAD

**Issue by knpausch** [streamr-turing/streamr-fe#74]
- [ ] Start on Share Modal
- [ ] Should see all users but not yourself
- [ ] Should be able to select friend
- [ ] Should be able to share to friend 
- [ ] Should be able to see "sent" message if successfully sent
- [ ] Should be able to see "failed" message if it was unsuccessful
- [ ] Should be able to close out modal

**Comment by Courtney-Lippman** [comment]
I am going to wait on share modal because I will need intercepts etc inorder to pull up the share modal.
